In [54]:
from scipy.linalg import solve
import numpy as np

In [55]:
a_a = np.array([[1, 2, 3], [4, 4, 2], [2, 1, -1]])
b_a = np.array([1, 2, 0])

In [56]:
S = solve(a_a, b_a)
S

array([-2.,  3., -1.])

In [70]:
def escalona(A,b):
  Ab = np.c_[A, b].astype(float)
  n = len(A)
  for c in range(n - 1):
    scope = np.abs(Ab[c:, c])
    maximum_index = scope.argmax() + c
    if c != maximum_index:
      Ab[[c, maximum_index]] = Ab[[maximum_index, c]]
    for l in range(c + 1, n):
      Ab[l] = Ab[l] - (Ab[l, c] / Ab[c, c]) * Ab[c]
  return Ab[:, :-1], Ab[:, -1]

In [58]:
A, b = escalona(a_a, b_a)
A, b

(array([[4, 4, 2],
        [0, 1, 2],
        [0, 0, 0]]),
 array([ 2,  0, -1]))

In [59]:
A @ S

array([2., 1., 0.])

In [66]:
exemplo_erro_A = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]])
exemplo_erro_B = np.array([1, 2, 0])
exemplo_erro_A, exemplo_erro_B

(array([[ 1,  1,  1],
        [ 4,  4,  2],
        [ 2,  1, -1]]),
 array([1, 2, 0]))

In [67]:
np.c_[exemplo_erro_A, exemplo_erro_B]

array([[ 1,  1,  1,  1],
       [ 4,  4,  2,  2],
       [ 2,  1, -1,  0]])

In [71]:
result_A, result_b = escalona(exemplo_erro_A, exemplo_erro_B)
result_A, result_b

(array([[ 4. ,  4. ,  2. ],
        [ 0. , -1. , -2. ],
        [ 0. ,  0. ,  0.5]]),
 array([ 2. , -1. ,  0.5]))

In [72]:
expected_result = solve(exemplo_erro_A, exemplo_erro_B)
expected_result

array([ 1., -1.,  1.])

In [73]:
expected_result @ result_A

array([4. , 5. , 4.5])